version: "3.9"

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${GRPC_PORT}:${GRPC_PORT}
    depends_on:
      - db
    command: [ "/app/main" ]
    networks:
      - network-stack

  db:
    image: postgres:14-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - network-stack

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - network-stack
    volumes:
      - ./redis-data:/data

networks:
  network-stack:
    driver: bridge
